import json
import pathlib

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

from swift_comet_pipeline.scp_types.primitive import *

from swift_comet_pipeline.data_ingestion.observation_log.observation_log_schema import (
    observation_log_schema,
)
from swift_comet_pipeline.swift.filters.uvot_filter_to_string import (
    filter_to_obs_string,
    obs_string_to_filter,
)
from swift_comet_pipeline.swift.swift_observation_id import (
    swift_observation_id_from_int,
)
from swift_comet_pipeline.swift.swift_orbit_id import swift_orbit_id_from_obsid
from swift_comet_pipeline.swift.uvot_datamodes import (
    datamode_from_fits_keyword_string,
    float_to_pixel_resolution,
)


def read_observation_log(
    obs_log_path: pathlib.Path,
) -> SwiftUvotObservationLogDataframe:
    """
    Reads an observation log generated by build_observation_log and converts column data types where needed
    """

    # obs_log = pd.read_parquet(obs_log_path, schema=schema, engine="pyarrow")

    # read the parquet file to a table, grab the metadata, and shove them both into a dataframe
    obs_log_table = pq.read_table(obs_log_path)
    encoded_metadata = obs_log_table.schema.metadata[b"pandas_attrs"]
    str_metadata = encoded_metadata.decode("utf-8")
    metadata = json.loads(str_metadata)
    obs_log = obs_log_table.to_pandas()
    obs_log.attrs = metadata

    # post-processing on the columns to get them into a datatype we want: we have to store these as strings
    # but datetime objects are much nicer to work with
    obs_log[["DATE_OBS", "DATE_END", "MID_TIME"]] = obs_log[
        ["DATE_OBS", "DATE_END", "MID_TIME"]
    ].apply(pd.to_datetime)

    # filters are stored as strings as well, convert them to UvotFilter objects
    obs_log.FILTER = obs_log["FILTER"].astype(str).map(obs_string_to_filter)

    # observation ID is stored as an int: convert to SwiftObservationID and SwiftOrbitID types
    obs_log.OBS_ID = obs_log["OBS_ID"].apply(swift_observation_id_from_int)
    obs_log["ORBIT_ID"] = obs_log["OBS_ID"].apply(swift_orbit_id_from_obsid)

    # ARCSECS_PER_PIXEL is stored as a float: convert to valid SwiftPixelResolution
    obs_log.ARCSECS_PER_PIXEL = obs_log.ARCSECS_PER_PIXEL.apply(
        float_to_pixel_resolution
    )

    # full paths as pathlib objects
    obs_log.FULL_FITS_PATH = obs_log.FULL_FITS_PATH.apply(pathlib.Path)

    # DATAMODE is stored as a string: convert to valid SwiftImageDataMode
    obs_log["DATAMODE"] = obs_log.apply(
        lambda row: datamode_from_fits_keyword_string(
            datamode=row.DATAMODE, fits_file_path=row.FULL_FITS_PATH
        ),
        axis=1,
    )

    return obs_log


def write_observation_log(
    obs_log: SwiftUvotObservationLogDataframe, obs_log_path: pathlib.Path
) -> None:
    """
    Copy obs_log and process the columns to data types that fit our schema, then save
    """
    oc = obs_log.copy()

    oc[["DATE_OBS", "DATE_END", "MID_TIME"]] = oc[
        ["DATE_OBS", "DATE_END", "MID_TIME"]
    ].astype(str)

    oc["OBS_ID"] = oc["OBS_ID"].astype(int)
    oc["FILTER"] = oc["FILTER"].map(filter_to_obs_string)

    oc.DATAMODE = oc.DATAMODE.astype(str)
    oc.ARCSECS_PER_PIXEL = oc.ARCSECS_PER_PIXEL.astype(float)

    oc.FULL_FITS_PATH = oc.FULL_FITS_PATH.astype(str)

    # Parquet requires serialized metadata, so store the dataframe's .attrs dict as json string
    # and add it to our schema, and save
    attrs_json = json.dumps(oc.attrs)
    s = observation_log_schema()
    schema = s.with_metadata({"pandas_attrs": attrs_json})
    t = pa.Table.from_pandas(oc, schema=schema)
    pq.write_table(t.cast(schema), obs_log_path)
